language: csharp
os: linux
dist: trusty
sudo: required
dotnet: 1.0.0-preview2-003121
mono: none
env: DOTNETCORE=1

script:
  - cd "dotnet-algorithms/dotnet-algorithms-tests" && pushd "dotnet-algorithms/dotnet-algorithms-tests"
  - dotnet restore
  - dotnet --verbose test 
  - popd 
